// Mock data for Digital Security Platform for Elderly

export const mockData = {
  // Navigation items
  navigation: [
    { id: 'inicio', name: 'Início', path: '/' },
    { id: 'conteudo', name: 'Conteúdo', path: '/conteudo' },
    { id: 'simulacoes', name: 'Simulações', path: '/simulacoes' },
    { id: 'quiz', name: 'Quiz', path: '/quiz' },
    { id: 'tutoriais', name: 'Tutoriais', path: '/tutoriais' },
    { id: 'pesquisas', name: 'Pesquisas', path: '/pesquisas' },
    { id: 'contato', name: 'Contato', path: '/contato' }
  ],

  // Hero section data
  hero: {
    title: 'Segurança Digital para Idosos',
    subtitle: 'Navegue com tranquilidade',
    buttonText: 'Começar'
  },

  // Main features
  features: [
    {
      id: 1,
      title: 'Aprenda sobre segurança digital',
      description: 'Conheça os principais riscos e como se proteger online',
      icon: 'BookOpen',
      color: 'bg-blue-50 border-blue-200',
      iconColor: 'text-blue-600'
    },
    {
      id: 2,
      title: 'Pratique com simulações interativas',
      description: 'Experimente situações reais em ambiente seguro',
      icon: 'Play',
      color: 'bg-green-50 border-green-200',
      iconColor: 'text-green-600'
    },
    {
      id: 3,
      title: 'Tutoriais passo-a-passo',
      description: 'Aprenda com guias detalhados e fáceis de seguir',
      icon: 'CheckSquare',
      color: 'bg-orange-50 border-orange-200',
      iconColor: 'text-orange-600'
    },
    {
      id: 4,
      title: 'Teste seus conhecimentos',
      description: 'Avalie seu aprendizado com questionários práticos',
      icon: 'Award',
      color: 'bg-purple-50 border-purple-200',
      iconColor: 'text-purple-600'
    }
  ],

  // QUIZ COMPLETO COM 30 PERGUNTAS
  quizQuestions: [
    // Módulo 1: Consciência de Segurança (6 perguntas)
    { id: 1, category: 'Conceitos Básicos', question: 'O que significa "HTTPS" no início de um endereço de site?', options: [{ id: 'a', text: 'Que o site é de alta velocidade.', isCorrect: false },{ id: 'b', text: 'Que o site é seguro para inserir informações.', isCorrect: true },{ id: 'c', text: 'Que o site tem muitas fotos.', isCorrect: false },{ id: 'd', text: 'Que é um site de compras.', isCorrect: false }], explanation: 'HTTPS significa que a conexão com o site é criptografada e segura.', wrongExplanation: 'O "S" em HTTPS significa "Seguro". Procure sempre por ele em sites que pedem dados.' },
    { id: 2, category: 'Privacidade', question: 'Qual informação é MAIS perigosa para compartilhar publicamente online?', options: [{ id: 'a', text: 'Sua comida favorita.', isCorrect: false },{ id: 'b', text: 'O nome do seu animal de estimação.', isCorrect: false },{ id: 'c', text: 'Seu endereço de casa e número de telefone.', isCorrect: true },{ id: 'd', text: 'O time para o qual você torce.', isCorrect: false }], explanation: 'Correto! Endereço e telefone são dados sensíveis.', wrongExplanation: 'Endereço e telefone são informações muito pessoais. Evite compartilhá-las publicamente.' },
    { id: 3, category: 'Wi-Fi Público', question: 'É seguro usar o Wi-Fi de um café para aceder à sua conta bancária?', options: [{ id: 'a', text: 'Sim, se a rede tiver senha.', isCorrect: false },{ id: 'b', text: 'Sim, se a conexão for rápida.', isCorrect: false },{ id: 'c', text: 'Não, redes públicas não são seguras para isso.', isCorrect: true },{ id: 'd', text: 'Sim, se ninguém estiver a olhar.', isCorrect: false }], explanation: 'Redes públicas podem ser facilmente interceptadas. Use sempre seus dados móveis para transações sensíveis.', wrongExplanation: 'Redes públicas não são seguras para informações sensíveis. Prefira usar seus dados móveis.' },
    { id: 4, category: 'Atualizações', question: 'Por que é importante manter seu computador e celular sempre atualizados?', options: [{ id: 'a', text: 'Para ter as funcionalidades mais recentes.', isCorrect: false },{ id: 'b', text: 'Para corrigir falhas de segurança.', isCorrect: true },{ id: 'c', text: 'Para deixar o aparelho mais rápido.', isCorrect: false },{ id: 'd', text: 'Não é importante, só ocupa espaço.', isCorrect: false }], explanation: 'As atualizações corrigem vulnerabilidades que os criminosos usam para atacar.', wrongExplanation: 'As atualizações são cruciais para corrigir falhas de segurança.' },
    { id: 5, category: 'Antivírus', question: 'Qual a principal função de um programa antivírus?', options: [{ id: 'a', text: 'Limpar ficheiros desnecessários.', isCorrect: false },{ id: 'b', text: 'Deixar a internet mais rápida.', isCorrect: false },{ id: 'c', text: 'Apenas remover pop-ups de propaganda.', isCorrect: false },{ id: 'd', text: 'Proteger contra softwares maliciosos.', isCorrect: true }], explanation: 'O antivírus detecta e remove programas maliciosos que podem roubar seus dados.', wrongExplanation: 'A função principal do antivírus é proteger seu dispositivo contra softwares maliciosos.' },
    { id: 6, category: 'Backup', question: 'O que é um "backup"?', options: [{ id: 'a', text: 'Uma cópia de segurança dos seus ficheiros.', isCorrect: true },{ id: 'b', text: 'Um programa de limpeza.', isCorrect: false },{ id: 'c', text: 'Uma atualização do sistema.', isCorrect: false },{ id: 'd', text: 'Um tipo de vírus.', isCorrect: false }], explanation: 'Backup é uma cópia de segurança que protege seus dados em caso de perda ou roubo.', wrongExplanation: 'Backup é uma cópia de segurança dos seus ficheiros importantes.' },
    // Módulo 2: Phishing (6 perguntas)
    { id: 7, category: 'Phishing', question: 'Você recebe um e-mail do "seu banco" a dizer que sua conta será bloqueada se não clicar num link. O que você faz?', options: [{ id: 'a', text: 'Clico no link para resolver logo.', isCorrect: false },{ id: 'b', text: 'Apago o e-mail e ligo para o meu gerente.', isCorrect: true },{ id: 'c', text: 'Respondo ao e-mail com meus dados.', isCorrect: false },{ id: 'd', text: 'Encaminho para um amigo para perguntar.', isCorrect: false }], explanation: 'Perfeito! Bancos nunca pedem dados por e-mail. A melhor ação é contatar o banco por canais oficiais.', wrongExplanation: 'Isto é um golpe clássico de phishing. Bancos nunca pedem dados por e-mail. Contate o banco por um canal oficial.' },
    { id: 8, category: 'Phishing', question: 'Qual destes remetentes de e-mail parece MAIS suspeito?', options: [{ id: 'a', text: 'contato@bancobrasil.com.br', isCorrect: false },{ id: 'b', text: 'seguranca@itau.com.br', isCorrect: false },{ id: 'c', text: 'nao-responda@caixa.gov.br', isCorrect: false },{ id: 'd', text: 'premio-bradesco@oferta-especial.com', isCorrect: true }], explanation: 'O domínio "oferta-especial.com" não tem relação com o Bradesco. É um sinal claro de fraude.', wrongExplanation: 'O domínio do e-mail (a parte depois do @) deve ser o oficial da empresa. "oferta-especial.com" é suspeito.' },
    { id: 9, category: 'Phishing', question: 'Uma mensagem de SMS oferece um prémio incrível se você aceder a um link. O que isso provavelmente é?', options: [{ id: 'a', text: 'Uma promoção real.', isCorrect: false },{ id: 'b', text: 'Um erro de envio.', isCorrect: false },{ id: 'c', text: 'Uma tentativa de golpe (Smishing).', isCorrect: true },{ id: 'd', text: 'Um aviso do seu plano de celular.', isCorrect: false }], explanation: 'Correto. Golpes por SMS são chamados de Smishing e usam promessas falsas para roubar dados.', wrongExplanation: 'Desconfie sempre de ofertas muito boas para serem verdade. É uma tática comum de golpe por SMS (Smishing).' },
    { id: 10, category: 'Phishing', question: 'O cadeado fechado e "HTTPS" no navegador garantem que o site é legítimo?', options: [{ id: 'a', text: 'Sim, sempre.', isCorrect: false },{ id: 'b', text: 'Não, apenas que a conexão é segura (criptografada).', isCorrect: true },{ id: 'c', text: 'Sim, mas só para sites de compras.', isCorrect: false },{ id: 'd', text: 'Não sei o que isso significa.', isCorrect: false }], explanation: 'Exato. Muitos sites falsos usam HTTPS para parecerem legítimos. É um fator importante, mas não o único.', wrongExplanation: 'HTTPS apenas garante que a conexão é segura. Criminosos também usam HTTPS em sites falsos para enganar. Verifique também o endereço do site.' },
    { id: 11, category: 'Phishing', question: 'Você recebe uma ligação a dizer que ganhou um sorteio e precisa de pagar uma "taxa" para receber. O que fazer?', options: [{ id: 'a', text: 'Pagar a taxa, é um valor baixo.', isCorrect: false },{ id: 'b', text: 'Pedir os dados para depósito.', isCorrect: false },{ id: 'c', text: 'Desligar, pois é um golpe.', isCorrect: true },{ id: 'd', text: 'Partilhar a novidade com a família primeiro.', isCorrect: false }], explanation: 'Sorteios e prémios legítimos nunca pedem pagamento de taxas antecipadas. Isso é um golpe de Vishing (phishing por voz).', wrongExplanation: 'Sorteios verdadeiros não cobram taxas para a entrega do prémio. É um golpe.' },
    { id: 12, category: 'Phishing', question: 'Um e-mail pede para você descarregar um anexo para ver uma "notificação judicial". Qual o risco?', options: [{ id: 'a', text: 'O anexo pode conter um vírus (malware).', isCorrect: true },{ id: 'b', text: 'O anexo pode ser muito pesado.', isCorrect: false },{ id: 'c', text: 'O anexo pode não ser compatível.', isCorrect: false },{ id: 'd', text: 'Não há risco, notificações judiciais são assim.', isCorrect: false }], explanation: 'Correto. Anexos inesperados, especialmente com temas urgentes, são a principal forma de infecção por malware.', wrongExplanation: 'Criminosos usam temas como "notificação judicial" para assustar e fazer com que você descarregue um vírus. Nunca abra anexos suspeitos.' },
    // Módulo 3: Malware (6 perguntas)
    { id: 13, category: 'Malware', question: 'O que é um "Ransomware"?', options: [{ id: 'a', text: 'Um antivírus gratuito.', isCorrect: false },{ id: 'b', text: 'Um tipo de vírus que "sequestra" seus ficheiros e pede resgate.', isCorrect: true },{ id: 'c', text: 'Um programa que deixa o PC mais rápido.', isCorrect: false },{ id: 'd', text: 'Uma propaganda que aparece na tela.', isCorrect: false }], explanation: 'Exato! Ransomware bloqueia o acesso aos seus ficheiros e exige um pagamento para liberá-los.', wrongExplanation: 'Ransomware é um tipo perigoso de vírus que "sequestra" seus ficheiros. A melhor defesa é ter um bom backup.' },
    { id: 14, category: 'Malware', question: 'Qual a forma mais segura de descarregar um programa para o computador?', options: [{ id: 'a', text: 'De links em vídeos do YouTube.', isCorrect: false },{ id: 'b', text: 'Do site oficial do desenvolvedor.', isCorrect: true },{ id: 'c', text: 'De programas que partilham ficheiros (torrents).', isCorrect: false },{ id: 'd', text: 'De banners de propaganda.', isCorrect: false }], explanation: 'Sempre descarregue do site oficial para garantir que você está a obter a versão legítima e sem vírus.', wrongExplanation: 'A forma mais segura é sempre ir diretamente ao site oficial do programa que você deseja descarregar.' },
    { id: 15, category: 'Malware', question: 'O que é um "Cavalo de Troia" (Trojan)?', options: [{ id: 'a', text: 'Um presente que se ganha online.', isCorrect: false },{ id: 'b', text: 'Um programa que parece útil, mas esconde um vírus.', isCorrect: true },{ id: 'c', text: 'Um jogo de cartas online.', isCorrect: false },{ id: 'd', text: 'Um antivírus antigo.', isCorrect: false }], explanation: 'Isso mesmo. Ele se disfarça de algo bom (como um jogo ou ferramenta) para enganá-lo e instalar um malware.', wrongExplanation: 'Assim como na história, o Cavalo de Troia é um programa que parece um presente, mas esconde uma ameaça dentro dele.' },
    { id: 16, category: 'Malware', question: 'O que é "Adware"?', options: [{ id: 'a', text: 'Um programa que mostra propagandas excessivas.', isCorrect: true },{ id: 'b', text: 'Um software de edição de fotos.', isCorrect: false },{ id: 'c', text: 'Um bloqueador de anúncios.', isCorrect: false },{ id: 'd', text: 'Um tipo de hardware.', isCorrect: false }], explanation: 'Adware é um software que exibe anúncios indesejados e pode deixar seu computador lento.', wrongExplanation: 'Adware vem de "advertisement" (propaganda). É um programa que inunda seu dispositivo com anúncios.' },
    { id: 17, category: 'Malware', question: 'O que fazer se você suspeita que seu computador foi infetado com um vírus?', options: [{ id: 'a', text: 'Continuar a usar normalmente.', isCorrect: false },{ id: 'b', text: 'Desligar da internet e rodar o antivírus.', isCorrect: true },{ id: 'c', text: 'Aceder ao site do banco para ver se está tudo bem.', isCorrect: false },{ id: 'd', text: 'Pedir ajuda num fórum online.', isCorrect: false }], explanation: 'Desconectar da internet impede que o vírus se espalhe ou envie seus dados. Em seguida, o antivírus deve ser executado.', wrongExplanation: 'A primeira ação é desconectar da internet. Depois, execute uma verificação completa com seu antivírus.' },
    { id: 18, category: 'Malware', question: 'Pen drives de desconhecidos são seguros para usar no seu computador?', options: [{ id: 'a', text: 'Sim, se a pessoa for simpática.', isCorrect: false },{ id: 'b', text: 'Sim, o computador avisa se tiver vírus.', isCorrect: false },{ id: 'c', text: 'Não, eles podem infetar o computador automaticamente.', isCorrect: true },{ id: 'd', text: 'Sim, se eu só for ver as fotos.', isCorrect: false }], explanation: 'Pen drives podem conter vírus que se executam automaticamente ao serem conectados. Nunca use um pen drive de origem desconhecida.', wrongExplanation: 'Nunca conecte um pen drive desconhecido ao seu computador. Ele pode conter vírus que se instalam sozinhos.' },
    // Módulo 4: Senhas (6 perguntas)
    { id: 19, category: 'Senhas', question: 'Qual destas senhas é a MAIS segura?', options: [{ id: 'a', text: '12345678', isCorrect: false },{ id: 'b', text: 'senhaforte', isCorrect: false },{ id: 'c', text: 'JoaoSilva1960', isCorrect: false },{ id: 'd', text: 'MeuC@chorroLat1uF0rte!', isCorrect: true }], explanation: 'Uma senha forte combina letras maiúsculas, minúsculas, números e símbolos, e é longa.', wrongExplanation: 'Senhas seguras são longas e misturam maiúsculas, minúsculas, números e símbolos.' },
    { id: 20, category: 'Senhas', question: 'É uma boa ideia usar a mesma senha para vários sites?', options: [{ id: 'a', text: 'Sim, facilita a memorização.', isCorrect: false },{ id: 'b', text: 'Sim, se a senha for muito forte.', isCorrect: false },{ id: 'c', text: 'Não, se um site for invadido, todas as suas contas ficam vulneráveis.', isCorrect: true },{ id: 'd', text: 'Não, mas só para sites de banco.', isCorrect: false }], explanation: 'Correto! Se um site fraco for invadido, os criminosos tentarão usar sua senha em todos os outros sites importantes.', wrongExplanation: 'Se você usa a mesma senha em todo o lado e um site é invadido, todas as suas contas ficam em risco. Use senhas diferentes.' },
    { id: 21, category: 'Senhas', question: 'O que é "Autenticação de Dois Fatores" (2FA)?', options: [{ id: 'a', text: 'Ter duas senhas para a mesma conta.', isCorrect: false },{ id: 'b', text: 'Uma camada extra de segurança, como um código no celular.', isCorrect: true },{ id: 'c', text: 'Um tipo de antivírus.', isCorrect: false },{ id: 'd', text: 'Uma verificação de impressão digital.', isCorrect: false }], explanation: 'Exato! Além da senha, você precisa de algo que só você tem, como seu celular, para provar que é você.', wrongExplanation: 'É uma segurança extra. Além da senha, você precisa de um código que chega no seu celular.' },
    { id: 22, category: 'Senhas', question: 'Onde é mais seguro guardar suas senhas?', options: [{ id: 'a', text: 'Num papel colado no monitor.', isCorrect: false },{ id: 'b', text: 'Num ficheiro de texto no computador chamado "senhas.txt".', isCorrect: false },{ id: 'c', text: 'Num gerenciador de senhas seguro.', isCorrect: true },{ id: 'd', text: 'Na memória, sem anotar em lugar nenhum.', isCorrect: false }], explanation: 'Gerenciadores de senhas são como cofres digitais que guardam suas senhas de forma criptografada.', wrongExplanation: 'Gerenciadores de senhas são a forma mais segura. Eles guardam tudo de forma criptografada e você só precisa de lembrar de uma senha mestra.' },
    { id: 23, category: 'Senhas', question: 'Com que frequência você deve trocar suas senhas importantes?', options: [{ id: 'a', text: 'Todos os dias.', isCorrect: false },{ id: 'b', text: 'A cada 6 meses a 1 ano, ou se suspeitar de algo.', isCorrect: true },{ id: 'c', text: 'Nunca, se ela for forte.', isCorrect: false },{ id: 'd', text: 'Apenas quando o site obriga.', isCorrect: false }], explanation: 'Trocar periodicamente suas senhas mais importantes (e-mail, banco) é uma boa prática de segurança.', wrongExplanation: 'É uma boa prática trocar senhas importantes, como a do seu e-mail principal, a cada 6 meses ou 1 ano.' },
    { id: 24, category: 'Senhas', question: 'O que fazer se você suspeita que a senha de uma de suas contas foi roubada?', options: [{ id: 'a', text: 'Esperar para ver o que acontece.', isCorrect: false },{ id: 'b', text: 'Mudar a senha imediatamente naquela conta e em outras onde a usava.', isCorrect: true },{ id: 'c', text: 'Apagar a conta.', isCorrect: false },{ id: 'd', text: 'Ligar para a polícia.', isCorrect: false }], explanation: 'A primeira ação é trocar a senha imediatamente para bloquear o acesso do invasor. Depois, troque em todos os outros sites onde usava a mesma senha.', wrongExplanation: 'Aja rápido! Troque a senha da conta afetada e de todas as outras onde você usava uma senha igual ou parecida.' },
    // Módulo 5: Engenharia Social (6 perguntas)
    { id: 25, category: 'Eng. Social', question: 'Um suposto "sobrinho" entra em contato por WhatsApp com um número novo a pedir dinheiro urgentemente. O que você faz?', options: [{ id: 'a', text: 'Transfiro o dinheiro, é uma emergência.', isCorrect: false },{ id: 'b', text: 'Ligo para o número antigo do meu sobrinho para confirmar.', isCorrect: true },{ id: 'c', text: 'Peço para ele me ligar para confirmar a voz.', isCorrect: true },{ id: 'd', text: 'As opções B e C estão corretas.', isCorrect: true }], explanation: 'Perfeito! Sempre confirme a identidade da pessoa por um meio diferente (ligação) antes de transferir dinheiro.', wrongExplanation: 'Este é o "Golpe do Novo Número". Sempre ligue para a pessoa (no número antigo ou peça para a pessoa ligar para você) para confirmar antes de enviar dinheiro.' },
    { id: 26, category: 'Eng. Social', question: 'Você vê um quiz no Facebook "Descubra qual celebridade você se parece!". Qual o risco?', options: [{ id: 'a', text: 'Nenhum, é só uma brincadeira.', isCorrect: false },{ id: 'b', text: 'Pode ser usado para coletar suas informações pessoais.', isCorrect: true },{ id: 'c', text: 'Pode deixar o Facebook mais lento.', isCorrect: false },{ id: 'd', text: 'Pode partilhar seu resultado com amigos.', isCorrect: false }], explanation: 'Muitos desses quizzes são criados para roubar dados, fazendo perguntas como "Qual o nome do seu primeiro animal de estimação?", que são respostas de perguntas de segurança.', wrongExplanation: 'Esses quizzes muitas vezes são iscas para coletar informações pessoais que podem ser usadas para redefinir suas senhas.' },
    { id: 27, category: 'Eng. Social', question: 'O que é o "Golpe do Amor" (Romance Scam)?', options: [{ id: 'a', text: 'Uma agência de casamentos.', isCorrect: false },{ id: 'b', text: 'Criminosos que criam perfis falsos para fingir um relacionamento e depois pedir dinheiro.', isCorrect: true },{ id: 'c', text: 'Um aplicativo de namoro seguro.', isCorrect: false },{ id: 'd', text: 'Um programa de TV.', isCorrect: false }], explanation: 'Exato. Os golpistas manipulam as emoções da vítima por meses antes de inventar uma emergência e pedir dinheiro.', wrongExplanation: 'É um golpe onde criminosos criam perfis falsos, fingem um relacionamento e, depois de ganhar a confiança da vítima, pedem dinheiro.' },
    { id: 28, category: 'Eng. Social', question: 'Um técnico da sua operadora de internet liga a pedir acesso remoto ao seu computador para "uma verificação". Você deve permitir?', options: [{ id: 'a', text: 'Sim, eles sabem o que estão a fazer.', isCorrect: false },{ id: 'b', text: 'Não, a menos que VOCÊ tenha ligado para eles a pedir ajuda primeiro.', isCorrect: true },{ id: 'c', text: 'Sim, se ele souber o meu nome completo.', isCorrect: false },{ id: 'd', text: 'Sim, mas só por 5 minutos.', isCorrect: false }], explanation: 'Empresas legítimas raramente ligam para oferecer suporte não solicitado. Desligue e ligue você mesmo para o número oficial da empresa para confirmar.', wrongExplanation: 'Nunca dê acesso remoto ao seu computador a alguém que ligou para você de surpresa. Se tiver um problema, VOCÊ deve ligar para a empresa.' },
    { id: 29, category: 'Eng. Social', question: 'Qual a melhor forma de se proteger contra a engenharia social?', options: [{ id: 'a', text: 'Ser desconfiado e verificar tudo antes de agir.', isCorrect: true },{ id: 'b', text: 'Não usar a internet.', isCorrect: false },{ id: 'c', text: 'Ter o melhor antivírus.', isCorrect: false },{ id: 'd', text: 'Acreditar na boa fé das pessoas.', isCorrect: false }], explanation: 'A principal defesa é a desconfiança saudável. Sempre pare, pense e verifique antes de clicar, partilhar ou pagar.', wrongExplanation: 'A melhor defesa é a sua desconfiança. Sempre que algo parecer urgente ou bom demais para ser verdade, pare e verifique.' },
    { id: 30, category: 'Eng. Social', question: 'Você recebe uma oferta de emprego incrível por mensagem, mas precisa de pagar por um "curso" primeiro. O que é isso?', options: [{ id: 'a', text: 'Uma ótima oportunidade.', isCorrect: false },{ id: 'b', text: 'Um procedimento padrão.', isCorrect: false },{ id: 'c', text: 'Um golpe para roubar seu dinheiro.', isCorrect: true },{ id: 'd', text: 'Um investimento na sua carreira.', isCorrect: false }], explanation: 'Empresas sérias nunca cobram para contratar alguém. Ofertas que pedem pagamento adiantado são sempre golpes.', wrongExplanation: 'Empresas legítimas não cobram para contratar você. Se pedem dinheiro adiantado, é um golpe.' }
  ]
};

export default mockData;